Repository endaoment/endaoment-contracts, pull requests merged in 2020-08, with the labels that each got.

#47 Audit Item L03
  contracts/Org.sol
Labels: audit

#49 Audit Item N01
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
Labels: audit

#50 Audit Item N03
  contracts/interfaces/IERC20.sol
  contracts/libraries/SafeMath.sol
Labels: audit

#51 Audit Item N04
  .gitignore
  .prettierrc
  .solhint.json
  contracts/Administratable.sol
  contracts/EndaomentAdmin.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
  contracts/interfaces/IEndaomentAdmin.sol
  contracts/mocks/ERC20Mock.sol
  package-lock.json
  package.json
Labels: audit

#53 Audit Item L01
  contracts/EndaomentAdmin.sol
  contracts/Fund.sol
  contracts/Org.sol
Labels: audit

#54 Audit Item L04
  contracts/Fund.sol
  contracts/Org.sol
Labels: audit

#52 Audit Item L08
  contracts/EndaomentAdmin.sol
  contracts/Fund.sol
  contracts/Org.sol
  test/Fund.test.js
  test/Org.test.js
Labels: audit

#55 Audit Item L09
  contracts/EndaomentAdmin.sol
  test/EndaomentAdmin.test.js
Labels: audit

#57 Audit Item L02
  README.md
  package-lock.json
Labels: audit

#59 Audit Item L02
  README.md
Labels: audit

#56 Audit Item L10
  contracts/Administratable.sol
Labels: audit

#61 Audit Item N07
  contracts/Fund.sol
  test/Fund.test.js
Labels: audit

#62 Audit Item N05
  contracts/EndaomentAdmin.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
Labels: audit

#60 Audit Item L02
  README.md
Labels: audit

#65 Audit Item L06
  contracts/Fund.sol
  contracts/FundFactory.sol
  test/OrgFactory.test.js
  test/fundFactory.test.js
Labels: audit

#66 Audit Item L07
  contracts/Org.sol
  test/Org.test.js
Labels: audit

#68 Audit Item H01
  contracts/Fund.sol
  contracts/Org.sol
Labels: audit

#63 Audit Item H02
  contracts/Fund.sol
  test/Fund.test.js
Labels: audit

#69 Audit Item H03
  contracts/Fund.sol
  contracts/Org.sol
Labels: audit

#64 Audit Item C02
  contracts/Fund.sol
Labels: audit

#73 Audit Item L06
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/OrgFactory.sol
  test/OrgFactory.test.js
  test/fundFactory.test.js
Labels: audit

#74 Audit Item M01
  contracts/Administratable.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  test/Fund.test.js
  test/Org.test.js
  test/OrgFactory.test.js
  test/fundFactory.test.js
Labels: audit

#76 Audit Item C01
  contracts/EndaomentAdminStorage.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/IFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
  test/EndaomentAdminStorage.test.js
  test/Fund.test.js
  test/Org.test.js
  test/OrgFactory.test.js
  test/fundFactory.test.js
Labels: audit

#75 Audit Item M02
  contracts/Administratable.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
  package-lock.json
  package.json
  test/Fund.test.js
  test/FundFactory.test.js
  test/Org.test.js
  test/OrgFactory.test.js
Labels: audit

#77 Audit Item C01 Addendum
  contracts/Fund.sol
  test/Fund.test.js
Labels: audit

#78 Audit Item L05
  README.md
  contracts/Administratable.sol
  contracts/EndaomentAdmin.sol
  contracts/EndaomentAdminStorage.sol
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
  contracts/interfaces/IFactory.sol
  docs/Administratable.md
  docs/EndaomentAdmin.md
  docs/EndaomentAdminStorage.md
  docs/Fund.md
  docs/FundFactory.md
  docs/Org.md
  docs/OrgFactory.md
  docs/contract.hbs
  docs/interfaces/IEndaomentAdmin.md
  docs/interfaces/IFactory.md
  docs/mocks/ERC20Mock.md
Labels: audit

#81 Update factory contracts to deploy EIP-1167 minimal proxies
  contracts/Fund.sol
  contracts/FundFactory.sol
  contracts/Org.sol
  contracts/OrgFactory.sol
  contracts/ProxyFactory.sol
  test/Fund.test.js
Labels: audit, enhancement

#83 changing ADMIN role in deploy script for new contracts post-audit
  deploy.js
  package-lock.json
Labels: enhancement
